language: java
jdk:
  - oraclejdk8
deploy:
  provider: releases
  api_key:
    secure: 1q4hlPaRmpvT7YrDOdfm7qIkZdh0+3DWZ0gFXmKTWJkIXH3MsGK2C0lXKX8fpsSzJJ9Nu2KHHOTva5fOHq1ZGZpItkkHc3fPsh71RIPJUj197/fI1xUimhKggV8t4Vq0r6J0iF0/0iI/+mRK5W+06HCsV4T2RgTTpkMfdmbFovCVD17Z/URMnS70KKjf/zOsJul/dIK0YoKKrddnP09iRDGc8MViST/d+ZIGS9K3tGofH/PO8pEbRBcuDhbV2hR69OMwFE5SNzpMIHL823ehzTDzE1H1SJ7/n/to90mYgU5jME7hYABuMS3VnTTGdUnHpxotyNXXM8fWPWN87hSXm1SuntE76oFopgNGTvaztRF3myGhXxLxfEB85IWEh4bqjqwL92I3SBfHvmFr0H6oZF2T3SwDt/sRTPYye8EdGQsRAS17fZUBQDaCKSmQX44W2D7FVy4IEeqCrga7q74er0edUiUidaMATA3mG2qbZth1Vv/xtF3greiFXKt6TzXsyFGTf4t+B5gDQNG9zyK66CPB3JQQD6axyUvCM8WM2fuuBn05pn7fHQKxTDLSOIGXqFPVUQmHRkaPmPLsUIyy/G052cuLsqrXySiZsjdIcVLg825iBerrRXYoVQdTOHuJORPdOEUdd6Bk/pH25r88FwXm9sKoJHvZKLN3i/Qow0o=
  file: "target/MCBingo.jar"
  skip_cleanup: true
  on:
    repo: Sunbread/MCBingo
    tags: true
