# Set the location of the lobby
# DO NOT set its world to "mcbingo_overworld" or "mcbingo_nether"
lobby-location:
  world: world
  x: 0.5
  y: 256.0
  z: 0.5
  yaw: 0.0
  pitch: 0.0
# Put item materials in bingo cards here
item-materials:
  - DIAMOND
  - DIAMOND_HOE
  - DIAMOND_AXE
  - BONE
  - GRAY_DYE
  - ENDER_PEARL
  - SLIME_BALL
  - FERN
  - VINE
  - DEAD_BUSH
  - BRICK
  - FLOWER_POT
  - GLASS_BOTTLE
  - MELON
  - GLISTERING_MELON_SLICE
  - INK_SAC
  - BOOK
  - WRITABLE_BOOK
  - APPLE
  - GOLDEN_SHOVEL
  - GOLDEN_APPLE
  - FLINT
  - FLINT_AND_STEEL
  - COCOA_BEANS
  - COOKIE
  - PUMPKIN_SEEDS
  - PUMPKIN_PIE
  - RAIL
  - MUSHROOM_STEW
  - SUGAR
  - SPIDER_EYE
  - FERMENTED_SPIDER_EYE
  - CACTUS_GREEN
  - LIME_DYE
  - LAPIS_LAZULI
  - PURPLE_DYE
  - CYAN_DYE
  - BEETROOT_SOUP
  - EMERALD
  - FURNACE_MINECART
  - CHEST_MINECART
  - TNT_MINECART
  - GUNPOWDER
  - FIREWORK_ROCKET
  - COMPASS
  - MAP
  - SPRUCE_SAPLING
  - ACACIA_SAPLING
  - CAULDRON
  - NAME_TAG
  - SADDLE
  - ENCHANTED_BOOK
  - MILK_BUCKET
  - EGG
  - CAKE
  - COD
  - SALMON
  - SIGN
  - ITEM_FRAME
  - PAINTING
  - GOLDEN_SWORD
  - CLOCK
  - POWERED_RAIL
  - HOPPER
  - HOPPER_MINECART
  - REPEATER